### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Hazzng** [bboylyg/NAD#13]
Hi i wonder what's the configuration of teacher and student or they are having the same architecture and train on the same train set

**Comment by bboylyg** [comment]
Hi, NAD uses the same model architecture for both the teacher and the student. The teacher model can be obtained by the student via fine-tuning on a clean subset. 
Note that NAD is also applicable to the teacher and student with different model architectures. In this case, an adaptive pooling layer can be adapted to reshape the size of attention maps in order to help the attention alignment.
