### ISSUE TITLE
Why is normalization not applied in the data preprocessing?

### ISSUE THREAD

**Issue by coldpark** [bboylyg/NAD#14]
I'd like to thank you for your great work on this project.

I noticed that during data preprocessing, normalization is not applied to the images. This seems unusual, as normalization is a common preprocessing step that helps improve the performance and stability of deep learning models.

Could you please provide an explanation for this decision? Is there a specific reason why normalization was not used in this case? Would it be beneficial to include normalization, or is it intentionally omitted for some reason?

Thank you in advance for your response.

**Comment by bboylyg** [comment]
Hi, thanks for your interest in our work. 

Yes, data normalization was not used for training a backdoored model because this is a default setting of previous research at that time in 2021.  You could definitely add various data augmentation techniques (e.g. flip, random crop, or data normalization) to train your backdoored model. We would gladly point out, in this case, our NAD also achieves consistent defense performance.

**Comment by coldpark** [comment]
Yes, your method also achieves consistent defense performance. Thanks for your reply.
